"""Runtime speech-provider settings for the dashboard.

The speech gateway reads provider choice from environment variables at process
start, so the dashboard persists an env file for the speech compose and a small
JSON file for UI state. API keys are stored in a separate 0600 file.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from reachy_voice.overrides import data_dir

SETTINGS_FILENAME = "speech_provider.json"
ENV_FILENAME = "speech.env"
DASHSCOPE_KEY_FILENAME = "dashscope_api_key"

DEFAULT_QWEN_URL = "wss://dashscope.aliyuncs.com/api-ws/v1/realtime"
DEFAULT_QWEN_MODEL = "qwen-audio-3.0-realtime-flash"
DEFAULT_QWEN_VOICE = "Serena"
DEFAULT_QWEN_COMPAT_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DEFAULT_QWEN_VISION_MODEL = "qwen3.5-omni-flash"


def settings_path() -> Path:
    return data_dir() / SETTINGS_FILENAME


def env_path() -> Path:
    return data_dir() / ENV_FILENAME


def dashscope_key_path() -> Path:
    return data_dir() / DASHSCOPE_KEY_FILENAME


def _defaults() -> dict[str, Any]:
    return {
        "mode": "local",
        "provider": "qwen",
        "qwen_url": DEFAULT_QWEN_URL,
        "qwen_model": DEFAULT_QWEN_MODEL,
        "qwen_voice": DEFAULT_QWEN_VOICE,
        "qwen_compat_url": DEFAULT_QWEN_COMPAT_URL,
        "qwen_vision_model": DEFAULT_QWEN_VISION_MODEL,
        "api_key_present": dashscope_key_path().exists(),
        "restart_required": False,
    }


def read_settings() -> dict[str, Any]:
    data = _defaults()
    try:
        loaded = json.loads(settings_path().read_text(encoding="utf-8"))
    except (FileNotFoundError, OSError, ValueError):
        loaded = {}
    if isinstance(loaded, dict):
        for key in (
            "mode",
            "provider",
            "qwen_url",
            "qwen_model",
            "qwen_voice",
            "qwen_compat_url",
            "qwen_vision_model",
        ):
            if loaded.get(key):
                data[key] = str(loaded[key])
        data["restart_required"] = bool(loaded.get("restart_required", False))
    data["api_key_present"] = dashscope_key_path().exists()
    return data


def _quote_env(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _write_env(settings: dict[str, Any]) -> None:
    mode = str(settings.get("mode") or "local").strip().lower()
    lines = [
        "# Generated by Reachy dashboard. Do not commit.",
        "OVS_REALTIME_PROVIDER=local",
    ]
    if mode == "online":
        key = dashscope_key_path().read_text(encoding="utf-8").strip()
        lines = [
            "# Generated by Reachy dashboard. Do not commit.",
            "OVS_REALTIME_PROVIDER=qwen",
            f"DASHSCOPE_API_KEY={_quote_env(key)}",
            f"OVS_REALTIME_QWEN_URL={_quote_env(str(settings['qwen_url']))}",
            f"OVS_REALTIME_QWEN_MODEL={_quote_env(str(settings['qwen_model']))}",
            f"OVS_REALTIME_QWEN_VOICE={_quote_env(str(settings['qwen_voice']))}",
        ]
    env_path().parent.mkdir(parents=True, exist_ok=True)
    env_path().write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(env_path(), 0o600)


def save_settings(payload: dict[str, Any]) -> dict[str, Any]:
    current = read_settings()
    mode = str(payload.get("mode") or current["mode"]).strip().lower()
    if mode not in {"local", "online"}:
        raise ValueError("mode must be local or online")

    current["mode"] = mode
    current["provider"] = "qwen"
    current["qwen_url"] = str(payload.get("qwen_url") or current["qwen_url"]).strip()
    current["qwen_model"] = str(payload.get("qwen_model") or current["qwen_model"]).strip()
    current["qwen_voice"] = str(payload.get("qwen_voice") or current["qwen_voice"]).strip()
    current["qwen_compat_url"] = str(
        payload.get("qwen_compat_url") or current["qwen_compat_url"]
    ).strip()
    current["qwen_vision_model"] = str(
        payload.get("qwen_vision_model") or current["qwen_vision_model"]
    ).strip()

    api_key = str(payload.get("api_key") or "").strip()
    if api_key:
        dashscope_key_path().parent.mkdir(parents=True, exist_ok=True)
        dashscope_key_path().write_text(api_key, encoding="utf-8")
        os.chmod(dashscope_key_path(), 0o600)

    if mode == "online" and not dashscope_key_path().exists():
        raise ValueError("DashScope API Key is required for online mode")

    current["restart_required"] = True
    settings_path().parent.mkdir(parents=True, exist_ok=True)
    settings_path().write_text(
        json.dumps(
            {k: v for k, v in current.items() if k != "api_key_present"},
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )
    _write_env(current)
    return read_settings()


def mark_applied() -> dict[str, Any]:
    current = read_settings()
    current["restart_required"] = False
    settings_path().write_text(
        json.dumps(
            {k: v for k, v in current.items() if k != "api_key_present"},
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )
    return read_settings()
