#!/usr/bin/env bash
# rebuild_deploy_reachy.sh — build the reachy-claw SLV image natively on the
# Jetson with the updated pyproject (reachy-mini 1.8.0) and redeploy ONLY the
# reachy-claw container. The reachy-daemon container is left running untouched.
#
# Safe-by-design:
#   * builds a NEW tag (slv-v8) — the current slv-v7 image stays as a rollback.
#   * deploys via a generated override file — the committed docker-compose.slv.yml
#     is NOT modified.
#   * `--no-deps reachy-claw` — daemon/other services are not recreated.
#
# PREREQUISITES on the Jetson:
#   * this repo checked out at REPO_DIR, on master with the 1.8.0 pyproject
#   * network access to a PyPI index with arm64 wheels (reachy-mini 1.8.0,
#     gstreamer-bundle 1.28.3, onnxruntime, mediapipe, …)
#   * scripts/backup_robot_reachy.sh already run (do the backup first!)
#
# Usage (run ON the Jetson):
#   REPO_DIR=~/clawd ./rebuild_deploy_reachy.sh
#   REPO_DIR=~/clawd NEW_TAG=slv-v8 ./rebuild_deploy_reachy.sh

set -euo pipefail

REPO_DIR="${REPO_DIR:-$HOME/clawd}"
IMAGE_BASE="${IMAGE_BASE:-sensecraft-missionpack.seeed.cn/solution/reachy-claw}"
NEW_TAG="${NEW_TAG:-slv-v8}"
DOCKERFILE="deploy/jetson/reachy/Dockerfile.reachy-claw.slv"
COMPOSE_DIR="$REPO_DIR/deploy/jetson/reachy"
here="$(cd "$(dirname "$0")" && pwd)"

[[ -d "$REPO_DIR/.git" ]] || { echo "REPO_DIR=$REPO_DIR is not a git checkout — set REPO_DIR"; exit 1; }
cd "$REPO_DIR"

# ── 0. sync repo to master (guarded) ─────────────────────────────────
echo "── repo state ──"
git status -sb | head -1
if [[ -n "$(git status --porcelain)" ]]; then
  echo "⚠ working tree has local changes (likely on-device config edits)."
  echo "  Not pulling automatically. Review 'git status' and pull manually if safe."
else
  echo "clean tree — pulling origin master…"
  git pull --ff-only origin master
fi

# ── 1. sanity: pyproject really pins 1.8.0 ───────────────────────────
if ! grep -qE 'reachy-mini>=1\.8' pyproject.toml; then
  echo "✗ pyproject.toml does not pin reachy-mini>=1.8 — aborting (wrong checkout?)"; exit 1
fi
echo "✓ pyproject pins: $(grep -E 'reachy-mini' pyproject.toml | tr -d ' ')"

# ── 2. build the new image (native arm64) ────────────────────────────
echo "── building $IMAGE_BASE:$NEW_TAG (this pulls 1.8.0 + arm64 wheels; takes a while) ──"
DOCKER_BUILDKIT=1 docker build -f "$DOCKERFILE" -t "$IMAGE_BASE:$NEW_TAG" "$REPO_DIR"

# verify the SDK version actually baked in
BAKED="$(docker run --rm --entrypoint python3 "$IMAGE_BASE:$NEW_TAG" -c 'import reachy_mini;print(reachy_mini.__version__)' 2>/dev/null || echo '?')"
echo "baked reachy-mini in new image: $BAKED"
[[ "$BAKED" == 1.8.* ]] || { echo "✗ new image did not bake reachy-mini 1.8.x (got '$BAKED') — NOT deploying"; exit 1; }

# ── 3. deploy ONLY reachy-claw via a non-destructive override ────────
OVERRIDE="$COMPOSE_DIR/docker-compose.slv.override.yml"
cat > "$OVERRIDE" <<EOF
# AUTO-GENERATED by rebuild_deploy_reachy.sh — pins reachy-claw to the freshly
# built tag without editing the committed compose. Delete to roll back.
services:
  reachy-claw:
    image: $IMAGE_BASE:$NEW_TAG
EOF
echo "wrote override: $OVERRIDE"

cd "$COMPOSE_DIR"
echo "── deploying reachy-claw ($NEW_TAG), daemon untouched ──"
docker compose -p reachy \
  -f docker-compose.yml -f docker-compose.slv.yml -f docker-compose.slv.override.yml \
  up -d --no-deps reachy-claw

echo "waiting for app to come up…"; sleep 8

# ── 4. verify ─────────────────────────────────────────────────────────
echo "── post-deploy verify ──"
bash "$here/verify_reachy_sdk.sh" || echo "(verify reported issues — see above)"

# ── 5. rollback instructions ─────────────────────────────────────────
cat <<EOF

Deployed $IMAGE_BASE:$NEW_TAG. Daemon was not touched.

ROLLBACK to the previous image (slv-v7):
  rm $OVERRIDE
  cd $COMPOSE_DIR
  docker compose -p reachy -f docker-compose.yml -f docker-compose.slv.yml up -d --no-deps reachy-claw
  # (if slv-v7 was pruned, first: docker load -i <backup>/image-claw.tar)

Optional smoke test with real motion (robot moves ~10°):
  bash $here/verify_reachy_sdk.sh --motion
EOF
